/*
 *  Puzzle-GIS - OpenSource mapping program
 *  http://docs.codehaus.org/display/PUZZLEGIS
 *  Copyright (C) 2007 Puzzle-GIS
 *  
 *  GPLv3 + Classpath exception
 *  
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.puzzle.puzzlemap2d.topcomponents;

import java.awt.BorderLayout;
import java.io.Serializable;
import java.util.logging.Logger;
import org.geotools.gui.swing.map.map2d.JDefaultEditableMap2D;
import org.geotools.gui.swing.map.map2d.control.JMap2DInfoBar;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.Utilities;
import org.puzzle.puzzlecore.struct.Application;
import org.puzzle.puzzlecore.struct.ApplicationContextEvent;
import org.puzzle.puzzlecore.struct.ApplicationContextListener;
import org.puzzle.puzzlemap2d.struct.Map2DManager;

/**
 * Top component which displays something.
 * @author johann sorel
 */
final class Map2DTopComponent extends TopComponent {

    private static Map2DTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";

    private static final String PREFERRED_ID = "Map2DTopComponent";
    private JDefaultEditableMap2D map2d;
    private JMap2DInfoBar infoBar;
    private ApplicationContextListener applicationListener = new ApplicationContextListener() {

        public void contextAdded(ApplicationContextEvent event) {
        }

        public void contextRemoved(ApplicationContextEvent event) {
        }

        public void contextActivated(ApplicationContextEvent event) {
            map2d.getRenderingStrategy().setContext(event.getMapContext());
        }

        public void contextMoved(ApplicationContextEvent event) {
        }
    };

    private Map2DTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(Map2DTopComponent.class, "CTL_Map2DTopComponent"));
        setToolTipText(NbBundle.getMessage(Map2DTopComponent.class, "HINT_Map2DTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
    
        setLayout(new BorderLayout());
    }

    private void initMap() {

        map2d = Map2DManager.getInstance().getMap2D();
        infoBar = Map2DManager.getInstance().getMapInfoBar();
        
        removeAll();
        add(BorderLayout.CENTER,map2d);
        add(BorderLayout.SOUTH,infoBar);

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized Map2DTopComponent getDefault() {
        if (instance == null) {
            instance = new Map2DTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the Map2DTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized Map2DTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(Map2DTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof Map2DTopComponent) {
            return (Map2DTopComponent) win;
        }
        Logger.getLogger(Map2DTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER;
    }

    @Override
    public void componentOpened() {
        initMap();
        Application.getInstance().addApplicationContextListener(applicationListener);
    }

    @Override
    public void componentClosed() {
        Application.getInstance().removeApplicationContextListener(applicationListener);
        map2d = null;
        infoBar = null;
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return Map2DTopComponent.getDefault();
        }
    }
}
