/*
 *  Puzzle-GIS - OpenSource mapping program
 *  http://docs.codehaus.org/display/PUZZLEGIS
 *  Copyright (C) 2007-2008 Puzzle-GIS
 *  
 *  GPLv3 + Classpath exception
 *  
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.puzzle.core.windows.mapdetail;

import java.awt.BorderLayout;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Logger;

import org.geotools.gui.swing.maptree.JContextTree;
import org.geotools.gui.swing.maptree.menu.DeleteItem;
import org.geotools.gui.swing.maptree.menu.LayerFeatureItem;
import org.geotools.gui.swing.maptree.menu.LayerPropertyItem;
import org.geotools.gui.swing.maptree.menu.SeparatorItem;
import org.geotools.gui.swing.propertyedit.LayerCRSPropertyPanel;
import org.geotools.gui.swing.propertyedit.LayerFilterPropertyPanel;
import org.geotools.gui.swing.propertyedit.LayerGeneralPanel;
import org.geotools.gui.swing.propertyedit.LayerStylePropertyPanel;
import org.geotools.gui.swing.propertyedit.PropertyPane;
import org.geotools.gui.swing.propertyedit.filterproperty.JCQLPropertyPanel;
import org.geotools.gui.swing.propertyedit.styleproperty.JAdvancedStylePanel;
import org.geotools.gui.swing.propertyedit.styleproperty.JSimpleStylePanel;

import org.openide.util.ImageUtilities;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle;
import org.openide.util.Utilities;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

import org.puzzle.core.project.filetype.GISContextDataObject;

/**
 * Top component which displays the context detail view.
 * 
 * @author : Johann Sorel (Puzzle-GIS)
 */
final class ContextTreeTopComponent extends TopComponent implements LookupListener{

    private Lookup.Result result = null;


    private JContextTree tree = null;
    private static ContextTreeTopComponent instance;
    private static final String PREFERRED_ID = "ContextTreeTopComponent";

    private ContextTreeTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(ContextTreeTopComponent.class, "contextTree"));
        setToolTipText(NbBundle.getMessage(ContextTreeTopComponent.class, "contextTreeHint"));
        setIcon(ImageUtilities.loadImage("org/puzzle/core/project/map.png", true));

    }

    public JContextTree getContextTree() {

        final JContextTree tree = new JContextTree();

        tree.controls().add(new LayerFeatureItem());
        tree.controls().add(new SeparatorItem());
        tree.controls().add(new DeleteItem(tree));
        tree.controls().add(new SeparatorItem());

        LayerPropertyItem property = new LayerPropertyItem();
        List<PropertyPane> lstproperty = new ArrayList<PropertyPane>();
        lstproperty.add(new LayerGeneralPanel());
        lstproperty.add(new LayerCRSPropertyPanel());

        LayerFilterPropertyPanel filters = new LayerFilterPropertyPanel();
        filters.addPropertyPanel(new JCQLPropertyPanel());
        lstproperty.add(filters);

        LayerStylePropertyPanel styles = new LayerStylePropertyPanel();
        styles.addPropertyPanel(new JSimpleStylePanel());
        styles.addPropertyPanel(new JAdvancedStylePanel());
//        styles.addPropertyPanel(new JXMLStylePanel());
        lstproperty.add(styles);

        property.setPropertyPanels(lstproperty);
        tree.controls().add(property);

        tree.revalidate();

        return tree;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized ContextTreeTopComponent getDefault() {
        if (instance == null) {
            instance = new ContextTreeTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the ContextTreeTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized ContextTreeTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(ContextTreeTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof ContextTreeTopComponent) {
            return (ContextTreeTopComponent) win;
        }
        Logger.getLogger(ContextTreeTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER;
    }

    @Override
    public void componentOpened() {
        result = Utilities.actionsGlobalContext().lookupResult(GISContextDataObject.class);
        result.addLookupListener (this);

        removeAll();
        if (tree == null) {
            tree = getContextTree();
        }

        add(BorderLayout.CENTER, tree);

        requestActive();
    }

    @Override
    public void componentClosed() {
        result.removeLookupListener (this);
        result = null;

        removeAll();
        tree = null;
    }

    @Override
    protected void componentShowing() {
        super.componentShowing();
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return ContextTreeTopComponent.getDefault();
        }
    }

    @Override
    public void resultChanged(LookupEvent lookupEvent) {
        final Lookup.Result r = (Lookup.Result) lookupEvent.getSource();
        final Collection c = r.allInstances();
        if (!c.isEmpty()) {

            new Thread(){

                public void run(){

                    final Iterator ite = c.iterator();
                    while(ite.hasNext()){
                        final GISContextDataObject da = (GISContextDataObject) ite.next();
                        tree.setContext(da.getContext());
                    }
                }

            }.start();
            
            
        }
    }

}
