/*
 *  Puzzle-GIS - OpenSource mapping program
 *  http://docs.codehaus.org/display/PUZZLEGIS
 *  Copyright (C) 2007-2008 Puzzle-GIS
 *  
 *  GPLv3 + Classpath exception
 *  
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.puzzle.shell.gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.IntrospectionException;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;
import javax.swing.JToolBar;
import javax.swing.SwingConstants;
import org.openide.explorer.propertysheet.PropertySheet;
import org.openide.nodes.BeanNode;
import org.openide.nodes.Node;
import org.openide.util.Exceptions;
import org.openide.util.NbBundle;
import org.puzzle.core.tool.ToolDescriptor;
import org.puzzle.shell.misc.runtime.JRuntimePanel;
import org.puzzle.shell.misc.runtime.ProcessEventListener;
import org.puzzle.shell.misc.runtime.ProcessObject;


/**
 *
 * @author johann sorel
 */
public class ShellToolPane extends javax.swing.JPanel implements PropertyChangeListener,ToolDescriptor{

    private final PropertySheet propertySheet = new PropertySheet();
    private ShellBean bean;
    
    /** Creates new form DefaultShellToolPane */
    public ShellToolPane() {
        initComponents();
        
        panBean.setLayout(new BorderLayout());
        panBean.add(BorderLayout.CENTER,propertySheet);
        
        panDOS.setLayout(new BorderLayout());        
    }

    public void setBean(ShellBean bean){
        
        if(this.bean != null){
            this.bean.removePropertyChangeListener(ShellBean.PROP_COMMAND,this);
        }
        
        this.bean = bean;
        
        if(this.bean != null){
            this.bean.addPropertyChangeListener(ShellBean.PROP_COMMAND,this);
        }
        
        
        
        Node node = null;
        try {
            node = new BeanNode<ShellBean>(bean);
        } catch (IntrospectionException ex) {
            Exceptions.printStackTrace(ex);
        }
        
        if(node != null){
            propertySheet.setNodes(new Node[]{node});
//            try {
//                propertySheet.setSortingMode(propertySheet.SORTED_BY_NAMES);
//            } catch (PropertyVetoException ex) {
//                Exceptions.printStackTrace(ex);
//            }
        }else{
            propertySheet.setNodes(new Node[]{});
        }
        
        
    }
    
    public ShellBean getBean(){
        return bean;
    }
    
    public void propertyChange(PropertyChangeEvent evt) {        
        String command =  (String) ((evt.getNewValue() == null) ? "" : evt.getNewValue());
        guiCommand.setText(command);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new JSplitPane();
        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        guiExec = new JButton();
        panBean = new JPanel();
        jToolBar1 = new JToolBar();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jSplitPane2 = new JSplitPane();
        jScrollPane1 = new JScrollPane();
        guiCommand = new JTextArea();
        panDOS = new JPanel();

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setDividerSize(8);

        jPanel1.setLayout(new BorderLayout());

        guiExec.setFont(guiExec.getFont().deriveFont(guiExec.getFont().getStyle() | Font.BOLD));
        guiExec.setIcon(new ImageIcon(getClass().getResource("/org/puzzle/shell/gui/runprog.png"))); // NOI18N
        guiExec.setText(NbBundle.getMessage(ShellToolPane.class, "exec")); // NOI18N
        guiExec.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                guiExecActionPerformed(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(guiExec)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guiExec)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, BorderLayout.PAGE_END);

        GroupLayout panBeanLayout = new GroupLayout(panBean);
        panBean.setLayout(panBeanLayout);
        panBeanLayout.setHorizontalGroup(
            panBeanLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        panBeanLayout.setVerticalGroup(
            panBeanLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );

        jPanel1.add(panBean, BorderLayout.CENTER);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new ImageIcon(getClass().getResource("/org/puzzle/shell/gui/fileexport.png"))); // NOI18N
        jButton1.setText(NbBundle.getMessage(ShellToolPane.class, "ShellToolPane.jButton1.text")); // NOI18N
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setIcon(new ImageIcon(getClass().getResource("/org/puzzle/shell/gui/fileopen.png"))); // NOI18N
        jButton2.setText(NbBundle.getMessage(ShellToolPane.class, "ShellToolPane.jButton2.text")); // NOI18N
        jButton2.setEnabled(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jPanel1.add(jToolBar1, BorderLayout.PAGE_START);

        jSplitPane1.setLeftComponent(jPanel1);

        jSplitPane2.setBorder(null);
        jSplitPane2.setOrientation(JSplitPane.VERTICAL_SPLIT);

        jScrollPane1.setBorder(null);

        guiCommand.setBackground(new Color(0, 0, 0));
        guiCommand.setColumns(20);
        guiCommand.setEditable(false);
        guiCommand.setForeground(new Color(255, 255, 255));
        guiCommand.setLineWrap(true);
        guiCommand.setRows(3);
        guiCommand.setBorder(null);
        jScrollPane1.setViewportView(guiCommand);

        jSplitPane2.setTopComponent(jScrollPane1);

        panDOS.setBackground(new Color(0, 0, 0));
        panDOS.setLayout(new GridLayout(1, 1));
        jSplitPane2.setBottomComponent(panDOS);

        jSplitPane1.setRightComponent(jSplitPane2);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addComponent(jSplitPane1, GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addComponent(jSplitPane1, GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void guiExecActionPerformed(ActionEvent evt) {//GEN-FIRST:event_guiExecActionPerformed
    
    if(bean != null){
        ProcessObject process = bean.createProcess();    
        JRuntimePanel runtime = new JRuntimePanel(process, JRuntimePanel.TYPE.LISTEN_BOTH);
        guiExec.setEnabled(false);
        
        panDOS.removeAll();
        panDOS.add(BorderLayout.CENTER,runtime);     
        panDOS.revalidate();
        panDOS.repaint();
        process.start();
        
        process.addProcessEventListener(new ProcessEventListener() {

                public void processStarted(ProcessObject obj) {
                }

                public void processStateUpdated(ProcessObject obj, String in, String out) {
                }

                public void processStopped(ProcessObject obj) {
                    
                    guiExec.setEnabled(true);
                }
            });
    }
    
}//GEN-LAST:event_guiExecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextArea guiCommand;
    private JButton guiExec;
    private JButton jButton1;
    private JButton jButton2;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JScrollPane jScrollPane1;
    private JSplitPane jSplitPane1;
    private JSplitPane jSplitPane2;
    private JToolBar jToolBar1;
    private JPanel panBean;
    private JPanel panDOS;
    // End of variables declaration//GEN-END:variables

    public String getTitle() {
        return bean.getTitle();
    }

    public String getDescription() {
        return bean.getDescription();
    }

    public String[] getPath() {
        return bean.getPath();
    }

    public String[] getKeyWords() {
        return bean.getKeyWords();
    }

    public String[] getCategories() {
        return bean.getCategories();
    }

    public Component getComponent() {
        return this;
    }

    public Image getIcon(int arg0) {
        return bean.getIcon(arg0);
    }



}
