/*
 *  Puzzle-GIS - OpenSource mapping program
 *  http://docs.codehaus.org/display/PUZZLEGIS
 *  Copyright (C) 2007-2008 Puzzle-GIS
 *  
 *  GPLv3 + Classpath exception
 *  
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.puzzle.shell.gdal.raster.folder;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import org.puzzle.shell.gdal.ENV;
import org.puzzle.shell.gdal.GDALTool;
import org.puzzle.shell.misc.runtime.ProcessObject;

/**
 * panneau  de convertion d'un fichier raster
 * @author romain govaere
 * @author johann sorel
 */
public class FolderRasterConvertTool extends JPanel implements GDALTool{
    
    String repertoire = "";
    
    /** Creates new form RasterConvDesFichiers */
    public FolderRasterConvertTool() {
        initComponents();
    }
    
    
    private void getFilesRec(List<File> allFiles, String root, boolean sub) {
        File f = new File(root);
        File[] listFiles = f.listFiles();
        for (int i = 0; i < listFiles.length; i++) {
            if (listFiles[i].isDirectory() && sub) getFilesRec(allFiles, listFiles[i].toString(),sub);
            else if ( !listFiles[i].isDirectory()) allFiles.add(listFiles[i]);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_entree = new javax.swing.JTextField();
        but_chercher_entree = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        format_sortie = new javax.swing.JComboBox();
        jtf_sortie = new javax.swing.JTextField();
        but_chercher_sortie = new javax.swing.JButton();
        format_entree = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        chk_sub = new javax.swing.JCheckBox();
        jXTitledSeparator1 = new org.jdesktop.swingx.JXTitledSeparator();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FolderRasterConvertTool.class, "files"))); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(FolderRasterConvertTool.class, "input")); // NOI18N

        but_chercher_entree.setText(org.openide.util.NbBundle.getMessage(FolderRasterConvertTool.class, "...")); // NOI18N
        but_chercher_entree.setPreferredSize(new java.awt.Dimension(45, 20));
        but_chercher_entree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_chercher_entreeactionChercherEntree(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(FolderRasterConvertTool.class, "output")); // NOI18N

        format_sortie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ERDAS IMAGINE (.img)", "ERMapper Compressed Wavelets (.ecw)", "Joint Photographic Experts Group (.jpg)", "JPEG2000 (.j2k .jp2)", "Portable Network Graphics (.png)", "GEOTIF (.tif)" }));
        format_sortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                format_sortieactionFormatSortie(evt);
            }
        });

        jtf_sortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_sortiesortieAction(evt);
            }
        });
        jtf_sortie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_sortiesortieLost(evt);
            }
        });

        but_chercher_sortie.setText(org.openide.util.NbBundle.getMessage(FolderRasterConvertTool.class, "...")); // NOI18N
        but_chercher_sortie.setPreferredSize(new java.awt.Dimension(45, 20));
        but_chercher_sortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_chercher_sortieactionChercherSortie(evt);
            }
        });

        format_entree.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ERDAS IMAGINE (.img)", "ERMapper Compressed Wavelets (.ecw)", "Joint Photographic Experts Group (.jpg)", "JPEG2000 (.j2k .jp2)", "Portable Network Graphics (.png)", "GEOTIF (.tif)" }));
        format_entree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                format_entreeactionFormatEntree(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(format_entree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jtf_entree, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_chercher_entree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(format_sortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jtf_sortie, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_chercher_sortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(format_entree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_chercher_entree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_entree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(format_sortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_chercher_sortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_sortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FolderRasterConvertTool.class, "settings"))); // NOI18N

        chk_sub.setSelected(true);
        chk_sub.setText(org.openide.util.NbBundle.getMessage(FolderRasterConvertTool.class, "subfolder")); // NOI18N
        chk_sub.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chk_sub.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chk_sub)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(chk_sub)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXTitledSeparator1.setTitle(org.openide.util.NbBundle.getMessage(FolderRasterConvertTool.class, "title")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXTitledSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXTitledSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
                
    private void format_entreeactionFormatEntree(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_format_entreeactionFormatEntree
        
    }//GEN-LAST:event_format_entreeactionFormatEntree
    
    private void but_chercher_sortieactionChercherSortie(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_chercher_sortieactionChercherSortie
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        jfc.setCurrentDirectory(ENV.getPath());
        
        int val = jfc.showOpenDialog(this);
        
        if(val == JFileChooser.APPROVE_OPTION){
            File f = jfc.getSelectedFile();
            jtf_sortie.setText( f.getPath() );
            ENV.updatePath(f.getAbsoluteFile());
            
        }
    }//GEN-LAST:event_but_chercher_sortieactionChercherSortie
    
    private void jtf_sortiesortieLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_sortiesortieLost
        
    }//GEN-LAST:event_jtf_sortiesortieLost
    
    private void jtf_sortiesortieAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_sortiesortieAction
        
    }//GEN-LAST:event_jtf_sortiesortieAction
    
    private void format_sortieactionFormatSortie(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_format_sortieactionFormatSortie
        
    }//GEN-LAST:event_format_sortieactionFormatSortie
    
    private void but_chercher_entreeactionChercherEntree(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_chercher_entreeactionChercherEntree
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        jfc.setCurrentDirectory(ENV.getPath());
        
        int val = jfc.showOpenDialog(this);
        
        if(val == JFileChooser.APPROVE_OPTION){
            File f = jfc.getSelectedFile();
            jtf_entree.setText( f.getPath() );
            ENV.updatePath(f.getAbsoluteFile());
        }
    }//GEN-LAST:event_but_chercher_entreeactionChercherEntree
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_chercher_entree;
    private javax.swing.JButton but_chercher_sortie;
    private javax.swing.JCheckBox chk_sub;
    private javax.swing.JComboBox format_entree;
    private javax.swing.JComboBox format_sortie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private org.jdesktop.swingx.JXTitledSeparator jXTitledSeparator1;
    private javax.swing.JTextField jtf_entree;
    private javax.swing.JTextField jtf_sortie;
    // End of variables declaration//GEN-END:variables

    public JComponent getComponent() {
        return this;
    }

    public ProcessObject[] createProcesses() {
        List<File> allfiles = new ArrayList<File>();
        List<String> okfiles = new ArrayList<String>();
        List<ProcessObject> processes = new ArrayList<ProcessObject>();
        
        String ext_entree = "";
        switch (format_entree.getSelectedIndex()){
            case 0 :ext_entree = ".img";break;
            case 1 :ext_entree = ".ecw";break;
            case 2 :ext_entree = ".jpg";break;
            case 3 :ext_entree = ".jp2";break;
            case 4 :ext_entree = ".png";break;
            case 5 :ext_entree = ".tif";break;
        }
        
        String type_sortie = "";
        String ext_sortie = "";
        switch (format_sortie.getSelectedIndex()){
            case 0 :type_sortie = "HFA"; ext_sortie = ".img"; break;
            case 1 :type_sortie = "ECW"; ext_sortie = ".ecw"; break;
            case 2 :type_sortie = "JPEG"; ext_sortie = ".jpg"; break;
            case 3 :type_sortie = "JPEG2000"; ext_sortie = ".j2k"; break;
            case 4 :type_sortie = "PNG"; ext_sortie = ".png"; break;
            case 5 :type_sortie = "GTiff"; ext_sortie = ".tif"; break;
        }
        
        
        getFilesRec(allfiles,jtf_entree.getText(),chk_sub.isSelected());
        
        for(int i=0; i<allfiles.size(); i++){
            if(allfiles.get(i).getPath().toLowerCase().endsWith(ext_entree)){
                okfiles.add(allfiles.get(i).getPath());
            }
        }
        
        for(int i=0; i<okfiles.size(); i++){
            
            repertoire = okfiles.get(i).substring(0, okfiles.get(i).lastIndexOf(File.separator)+1 );
            
            String shortname = okfiles.get(i).substring( okfiles.get(i).lastIndexOf(File.separator) ,okfiles.get(i).length() );
            shortname = shortname.substring(0, shortname.lastIndexOf(".")) + ext_sortie;
            
            
            String[] parametres = new String[5];
            parametres[0] = ENV.getGDAL_TRANSLATEPath();
            parametres[1] = "-of";
            parametres[2] = type_sortie;
            parametres[3] = okfiles.get(i);
            parametres[4] = jtf_sortie.getText() + shortname;
            
            ProcessObject po = new ProcessObject(parametres,shortname);
            
            processes.add(po);
        }
        
        return processes.toArray(EMPTY_PROCESS_OBJECT_ARRAY);
    }
    
}
