/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.puzzle.puzzlecore.gui.minimap;

import java.awt.BorderLayout;
import java.io.Serializable;
import java.util.logging.Logger;
import org.geotools.gui.swing.map.map2d.minimap.JMiniMap;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.Utilities;
import org.puzzle.puzzlecore.struct.CORE;
import org.puzzle.puzzlecore.struct.GroupEvent;
import org.puzzle.puzzlecore.struct.ViewEvent;
import org.puzzle.puzzlecore.struct.ViewListener;
import org.puzzle.puzzlecore.struct.ViewManager;

/**
 * Top component which displays something.
 */
final class MiniMapTopComponent extends TopComponent {

    private JMiniMap map = null;
    
    private ViewListener listener = null;
    
    private static MiniMapTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";

    private static final String PREFERRED_ID = "MiniMapTopComponent";

    private MiniMapTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(MiniMapTopComponent.class, "CTL_MiniMapTopComponent"));
        setToolTipText(NbBundle.getMessage(MiniMapTopComponent.class, "HINT_MiniMapTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized MiniMapTopComponent getDefault() {
        if (instance == null) {
            instance = new MiniMapTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the MiniMapTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized MiniMapTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(MiniMapTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof MiniMapTopComponent) {
            return (MiniMapTopComponent) win;
        }
        Logger.getLogger(MiniMapTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        removeAll();
        if(map == null){
            map = new JMiniMap();
            listener = new ViewListener() {

                public void viewAdded(ViewEvent event) {
                }

                public void viewRemoved(ViewEvent event) {
                }

                public void viewActivated(ViewEvent event) {
                    map.setRelatedMap2D(event.getView().getMap());
                }

                public void groupAdded(GroupEvent event) {
                }

                public void groupRemoved(GroupEvent event) {
                }

                public void groupChanged(GroupEvent event) {
                }
            };
            
            CORE.getViewManager().addViewListener(listener);
            
        }
        
        add(BorderLayout.CENTER,map);
    }

    @Override
    public void componentClosed() {
        removeAll();
        map = null;
        
        CORE.getViewManager().removeViewListener(listener);
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return MiniMapTopComponent.getDefault();
        }
    }
}
