/*
 *  Puzzle-GIS - OpenSource mapping program
 *  http://docs.codehaus.org/display/PUZZLEGIS
 *  Copyright (C) 2007-2008 Puzzle-GIS
 *  
 *  GPLv3 + Classpath exception
 *  
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.puzzle.shell.gdal.vector.folder;

import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import org.jdesktop.swingx.JXTitledSeparator;
import org.openide.util.NbBundle;
import org.puzzle.shell.gdal.ENV;
import org.puzzle.shell.gdal.GDALTool;
import org.puzzle.shell.misc.runtime.ProcessObject;

/**
 * panneau de convertion de vecteur par dossier
 * @author  johann sorel
 */
public class FolderVectorConvertTool extends JPanel implements GDALTool {

    String repertoire = "";

    /** Creates new form VecteurConvDesFichiers */
    public FolderVectorConvertTool() {
        initComponents();
    }

    private void getFilesRec(List<File> allFiles, String root, boolean sub) {
        File f = new File(root);
        File[] listFiles = f.listFiles();
        for (int i = 0; i < listFiles.length; i++) {
            if (listFiles[i].isDirectory() && sub) {
                getFilesRec(allFiles, listFiles[i].toString(), sub);
            } else if (!listFiles[i].isDirectory()) {
                allFiles.add(listFiles[i]);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {




        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jtf_entree = new JTextField();
        but_chercher_entree = new JButton();
        jLabel2 = new JLabel();
        format_sortie = new JComboBox();
        jtf_sortie = new JTextField();
        but_chercher_sortie = new JButton();
        format_entree = new JComboBox();
        jPanel2 = new JPanel();
        chk_sub = new JCheckBox();
        jXTitledSeparator1 = new JXTitledSeparator();

        jPanel1.setBorder(BorderFactory.createTitledBorder(NbBundle.getMessage(FolderVectorConvertTool.class, "files"))); // NOI18N
        jLabel1.setText(NbBundle.getMessage(FolderVectorConvertTool.class, "input")); // NOI18N
        but_chercher_entree.setText(NbBundle.getMessage(FolderVectorConvertTool.class, "...")); // NOI18N
        but_chercher_entree.setPreferredSize(new Dimension(45, 20));
        but_chercher_entree.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                actionChercherEntree(evt);
            }
        });

        jLabel2.setText(NbBundle.getMessage(FolderVectorConvertTool.class, "output")); // NOI18N
        format_sortie.setModel(new DefaultComboBoxModel(new String[] { "MicroStation (.dgn)", "Geography Markup Language (.gml)", "Google Earth / Map  (.kml)", "MapInfo Exchange (.mif)", "ESRI Shape (.shp)", "MapInfo (.tab)" }));
        format_sortie.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                actionFormatSortie(evt);
            }
        });

        jtf_sortie.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jtf_sortiesortieAction(evt);
            }
        });
        jtf_sortie.addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent evt) {
                jtf_sortiesortieLost(evt);
            }
        });

        but_chercher_sortie.setText(NbBundle.getMessage(FolderVectorConvertTool.class, "...")); // NOI18N
        but_chercher_sortie.setPreferredSize(new Dimension(45, 20));
        but_chercher_sortie.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                actionChercherSortie(evt);
            }
        });

        format_entree.setModel(new DefaultComboBoxModel(new String[] { "MicroStation (.dgn)", "Geography Markup Language (.gml)", "Google Earth / Map  (.kml)", "MapInfo Exchange(.mif)", "ESRI Shape (.shp)", "MapInfo (.tab)" }));
        format_entree.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                actionFormatEntree(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);

        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(format_entree, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jtf_entree, GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(but_chercher_entree, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(format_sortie, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jtf_sortie, GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(but_chercher_sortie, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(format_entree, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(but_chercher_entree, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_entree, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(format_sortie, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(but_chercher_sortie, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_sortie, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBorder(BorderFactory.createTitledBorder(NbBundle.getMessage(FolderVectorConvertTool.class, "settings"))); // NOI18N
        chk_sub.setSelected(true);
        chk_sub.setText(NbBundle.getMessage(FolderVectorConvertTool.class, "subfolder")); // NOI18N
        chk_sub.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chk_sub.setMargin(new Insets(0, 0, 0, 0));

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);

        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chk_sub)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(chk_sub)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXTitledSeparator1.setTitle(NbBundle.getMessage(FolderVectorConvertTool.class, "title")); // NOI18N
        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jXTitledSeparator1, GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXTitledSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actionFormatEntree(ActionEvent evt) {//GEN-FIRST:event_actionFormatEntree
    }//GEN-LAST:event_actionFormatEntree

    private void actionChercherSortie(ActionEvent evt) {//GEN-FIRST:event_actionChercherSortie
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        jfc.setCurrentDirectory(ENV.getPath());

        int val = jfc.showOpenDialog(this);

        if (val == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            jtf_sortie.setText(f.getPath());
            ENV.updatePath(f.getAbsoluteFile());

        }
    }//GEN-LAST:event_actionChercherSortie

    private void jtf_sortiesortieLost(FocusEvent evt) {//GEN-FIRST:event_jtf_sortiesortieLost
    }//GEN-LAST:event_jtf_sortiesortieLost

    private void jtf_sortiesortieAction(ActionEvent evt) {//GEN-FIRST:event_jtf_sortiesortieAction
    }//GEN-LAST:event_jtf_sortiesortieAction

    private void actionFormatSortie(ActionEvent evt) {//GEN-FIRST:event_actionFormatSortie
    }//GEN-LAST:event_actionFormatSortie

    private void actionChercherEntree(ActionEvent evt) {//GEN-FIRST:event_actionChercherEntree
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        jfc.setCurrentDirectory(ENV.getPath());

        int val = jfc.showOpenDialog(this);

        if (val == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            jtf_entree.setText(f.getPath());
            ENV.updatePath(f.getAbsoluteFile());
        }
    }//GEN-LAST:event_actionChercherEntree
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton but_chercher_entree;
    private JButton but_chercher_sortie;
    private JCheckBox chk_sub;
    private JComboBox format_entree;
    private JComboBox format_sortie;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JXTitledSeparator jXTitledSeparator1;
    private JTextField jtf_entree;
    private JTextField jtf_sortie;
    // End of variables declaration//GEN-END:variables

    public JComponent getComponent() {
        return this;
    }

    public ProcessObject[] createProcesses() {
        List<File> allfiles = new ArrayList<File>();
        List<String> okfiles = new ArrayList<String>();
        List<ProcessObject> processes = new ArrayList<ProcessObject>();
        

        String ext_entree = "";

        switch (format_entree.getSelectedIndex()) {
            case 0:
                ext_entree = ".dgn";
                break;
            case 1:
                ext_entree = ".gml";
                break;
            case 2:
                ext_entree = ".kml";
                break;
            case 3:
                ext_entree = ".mif";
                break;
            case 4:
                ext_entree = ".shp";
                break;
            case 5:
                ext_entree = ".tab";
                break;
        }


        String type_sortie = "";
        String ext_sortie = "";
        switch (format_sortie.getSelectedIndex()) {
            case 0:
                type_sortie = "DGN";
                ext_sortie = ".dgn";
                break;
            case 1:
                type_sortie = "GML";
                ext_sortie = ".gml";
                break;
            case 2:
                type_sortie = "KML";
                ext_sortie = ".kml";
                break;
            case 3:
                type_sortie = "MapInfo File";
                ext_sortie = ".mif";
                break;
            case 4:
                type_sortie = "ESRI Shapefile";
                ext_sortie = ".shp";
                break;
            case 5:
                type_sortie = "MapInfo File";
                ext_sortie = ".tab";
                break;
        }


        getFilesRec(allfiles, jtf_entree.getText(), chk_sub.isSelected());

        for (int i = 0; i < allfiles.size(); i++) {
            if (allfiles.get(i).getPath().toLowerCase().endsWith(ext_entree)) {
                okfiles.add(allfiles.get(i).getPath());
            }
        }

        for (int i = 0; i < okfiles.size(); i++) {
            repertoire = okfiles.get(i).substring(0, okfiles.get(i).lastIndexOf(File.separator));
            String shortname = okfiles.get(i).substring(okfiles.get(i).lastIndexOf(File.separator), okfiles.get(i).length());
            shortname = shortname.substring(0, shortname.lastIndexOf(".")) + ext_sortie;


            String[] parametres = new String[5];
            parametres[0] = ENV.getOGR2OGRPath();
            parametres[1] = "-f";
            parametres[2] = type_sortie;
            parametres[3] = jtf_sortie.getText() + shortname;
            parametres[4] = okfiles.get(i);

            ProcessObject po = new ProcessObject(parametres, shortname);

            processes.add(po);
        }

        return processes.toArray(EMPTY_PROCESS_OBJECT_ARRAY);
    }
}
