/*
 *  Puzzle-GIS - OpenSource mapping program
 *  http://docs.codehaus.org/display/PUZZLEGIS
 *  Copyright (C) 2007-2008 Puzzle-GIS
 *  
 *  GPLv3 + Classpath exception
 *  
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.puzzle.shell.gdal.raster.mnt;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SpinnerNumberModel;
import javax.swing.border.TitledBorder;
import org.geotools.gui.swing.misc.filter.FileFilterFactory;
import org.geotools.gui.swing.misc.filter.FileFilterFactory.FORMAT;
import org.jdesktop.swingx.JXTitledSeparator;
import org.openide.util.NbBundle;
import org.puzzle.shell.gdal.ENV;
import org.puzzle.shell.gdal.GDALTool;
import org.puzzle.shell.misc.runtime.ProcessObject;

/**
 * panneau de convertion MNT ESRI ASCII GRID 
 * @author  johann sorel
 */
public class RasterToMntTool extends JPanel implements GDALTool {

    String repertoire = "";

    /** Creates new form MNTConvertionUnFichier */
    public RasterToMntTool() {
        initComponents();

    }

    private void rm_testName() {
        String nom_sortie = rm_jtf_sortie.getText();
        String nom_entree = rm_jtf_entree.getText();
        String extension_fichier = "";
        String extension_liste = "";
        String nouveaunom = "";
        int index = -1;

        //recuperation de l'extension dans la liste
        int num = rm_format.getSelectedIndex();
        switch (num) {
            case 0:
                extension_liste = ".asc";
                break;
        }

        //si le texte en sortie est vide on le complete avec celui d'entree
        if (nom_sortie.length() == 0) {
            nom_sortie = nom_entree;
        }

        //recuperation de l'extension du fichier en sortie
        index = nom_sortie.lastIndexOf(".");
        if (index != -1) {
            extension_fichier = nom_sortie.substring(index, nom_sortie.length());
        }


        // on corrige l'extension
        if (!nom_sortie.endsWith(extension_liste)) {

            if (nom_sortie.endsWith(File.separator)) {
                nom_sortie += "sortie";
            }

            if (!nom_sortie.equals("")) {
                if (index == -1) {

                    nouveaunom = nom_sortie + extension_liste;
                } else {
                    nouveaunom = nom_sortie.substring(0, index) + extension_liste;
                }
            }

        } else {
            nouveaunom = nom_sortie;
        }

        rm_jtf_sortie.setText(nouveaunom);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {




        jPanel1 = new JPanel();
        rm_chercher = new JButton();
        rm_jtf_sortie = new JTextField();
        rm_jtf_entree = new JTextField();
        jLabel2 = new JLabel();
        jLabel1 = new JLabel();
        rm_format = new JComboBox();
        rm_chercher_sortie = new JButton();
        pan_detail = new JPanel();
        guiBand = new JSpinner();
        jLabel3 = new JLabel();
        jXTitledSeparator1 = new JXTitledSeparator();

        jPanel1.setBorder(BorderFactory.createTitledBorder(NbBundle.getMessage(RasterToMntTool.class, "files"))); // NOI18N
        rm_chercher.setText(NbBundle.getMessage(RasterToMntTool.class, "...")); // NOI18N
        rm_chercher.setPreferredSize(new Dimension(45, 20));
        rm_chercher.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                rm_chercher_entree(evt);
            }
        });

        rm_jtf_sortie.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                rm_sortieaction(evt);
            }
        });
        rm_jtf_sortie.addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent evt) {
                rm_sortielost(evt);
            }
        });

        jLabel2.setText(NbBundle.getMessage(RasterToMntTool.class, "output")); // NOI18N
        jLabel1.setText(NbBundle.getMessage(RasterToMntTool.class, "input")); // NOI18N
        rm_format.setModel(new DefaultComboBoxModel(new String[] { "ESRI ASCII GRID (.asc)" }));
        rm_format.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                rm_choix(evt);
            }
        });

        rm_chercher_sortie.setText(NbBundle.getMessage(RasterToMntTool.class, "...")); // NOI18N
        rm_chercher_sortie.setPreferredSize(new Dimension(45, 20));
        rm_chercher_sortie.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                rm_chercher_sortie(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);


        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rm_jtf_sortie, GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(rm_chercher_sortie, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(rm_format, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rm_jtf_entree, GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(rm_chercher, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(rm_chercher, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(rm_jtf_entree, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(rm_format, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(rm_jtf_sortie, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(rm_chercher_sortie, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan_detail.setBorder(BorderFactory.createTitledBorder(null, "Configuration", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Dialog", 1, 11))); // NOI18N
        guiBand.setModel(new SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel3.setText(NbBundle.getMessage(RasterToMntTool.class, "band")); // NOI18N
        GroupLayout pan_detailLayout = new GroupLayout(pan_detail);
        pan_detail.setLayout(pan_detailLayout);

        pan_detailLayout.setHorizontalGroup(
            pan_detailLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pan_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(guiBand, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        pan_detailLayout.setVerticalGroup(
            pan_detailLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(pan_detailLayout.createSequentialGroup()
                .addGroup(pan_detailLayout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(guiBand, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXTitledSeparator1.setTitle(NbBundle.getMessage(RasterToMntTool.class, "rastertomnt")); // NOI18N
        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(pan_detail, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTitledSeparator1, GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXTitledSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(pan_detail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void rm_chercher_sortie(ActionEvent evt) {//GEN-FIRST:event_rm_chercher_sortie
    JFileChooser jfc = new JFileChooser();
    jfc.addChoosableFileFilter(FileFilterFactory.createFileFilter(FORMAT.ERMAPPER_COMPRESSED_WAVELETS));
    jfc.addChoosableFileFilter(FileFilterFactory.createFileFilter(FORMAT.ERDAS_IMAGE));
    jfc.addChoosableFileFilter(FileFilterFactory.createFileFilter(FORMAT.JOINT_PHOTOGRAPHIC_EXPERTS_GROUP));
    jfc.addChoosableFileFilter(FileFilterFactory.createFileFilter(FORMAT.JPEG_2000));
    jfc.addChoosableFileFilter(FileFilterFactory.createFileFilter(FORMAT.PORTABLE_NETWORK_GRAPHICS));
    jfc.addChoosableFileFilter(FileFilterFactory.createFileFilter(FORMAT.TIFF));

    jfc.setFileFilter(jfc.getChoosableFileFilters()[0]);

    jfc.setCurrentDirectory(ENV.getPath());

    int val = jfc.showSaveDialog(this);

    if (val == JFileChooser.APPROVE_OPTION) {
        File f = jfc.getSelectedFile();
        rm_jtf_sortie.setText(f.getPath());
        rm_testName();
        ENV.updatePath(f.getAbsoluteFile());
    }
}//GEN-LAST:event_rm_chercher_sortie

private void rm_choix(ActionEvent evt) {//GEN-FIRST:event_rm_choix
    rm_testName();
}//GEN-LAST:event_rm_choix

private void rm_sortielost(FocusEvent evt) {//GEN-FIRST:event_rm_sortielost
    rm_testName();
}//GEN-LAST:event_rm_sortielost

private void rm_sortieaction(ActionEvent evt) {//GEN-FIRST:event_rm_sortieaction
    rm_testName();
}//GEN-LAST:event_rm_sortieaction

private void rm_chercher_entree(ActionEvent evt) {//GEN-FIRST:event_rm_chercher_entree
    JFileChooser jfc = new JFileChooser();
    jfc.addChoosableFileFilter(FileFilterFactory.createFileFilter(FORMAT.ERMAPPER_COMPRESSED_WAVELETS));
    jfc.addChoosableFileFilter(FileFilterFactory.createFileFilter(FORMAT.ERDAS_IMAGE));
    jfc.addChoosableFileFilter(FileFilterFactory.createFileFilter(FORMAT.JOINT_PHOTOGRAPHIC_EXPERTS_GROUP));
    jfc.addChoosableFileFilter(FileFilterFactory.createFileFilter(FORMAT.JPEG_2000));
    jfc.addChoosableFileFilter(FileFilterFactory.createFileFilter(FORMAT.PORTABLE_NETWORK_GRAPHICS));
    jfc.addChoosableFileFilter(FileFilterFactory.createFileFilter(FORMAT.TIFF));

    jfc.setCurrentDirectory(ENV.getPath());

    jfc.setFileFilter(jfc.getChoosableFileFilters()[0]);


    int val = jfc.showOpenDialog(this);

    if (val == JFileChooser.APPROVE_OPTION) {
        File f = jfc.getSelectedFile();
        rm_jtf_entree.setText(f.getPath());
        rm_testName();
        ENV.updatePath(f.getAbsoluteFile());
    }
}//GEN-LAST:event_rm_chercher_entree
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JSpinner guiBand;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JPanel jPanel1;
    private JXTitledSeparator jXTitledSeparator1;
    private JPanel pan_detail;
    private JButton rm_chercher;
    private JButton rm_chercher_sortie;
    private JComboBox rm_format;
    private JTextField rm_jtf_entree;
    private JTextField rm_jtf_sortie;
    // End of variables declaration//GEN-END:variables
    
    public JComponent getComponent() {
        return this;
    }

    public ProcessObject[] createProcesses() {
        if (rm_jtf_entree.getText().equals("") || rm_jtf_sortie.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs", "Donnees manquantes", JOptionPane.ERROR_MESSAGE);
            return EMPTY_PROCESS_OBJECT_ARRAY;
        } else {

            String format_sortie = "";
            switch (rm_format.getSelectedIndex()) {
                case 0:
                    format_sortie = "AAIGrid";
                    break;
            }

            String[] parametres = new String[7];
            parametres[0] = ENV.getGDAL_TRANSLATEPath();
            parametres[1] = "-of";
            parametres[2] = format_sortie;
            parametres[3] = "-b";
            parametres[4] = String.valueOf(guiBand.getValue());
            parametres[5] = rm_jtf_entree.getText();
            parametres[6] = rm_jtf_sortie.getText();
            String separateur = File.separator;
            int i = rm_jtf_sortie.getText().lastIndexOf(separateur);

            repertoire = rm_jtf_sortie.getText().substring(0, i - 1);
            String nom = rm_jtf_sortie.getText().substring(i + 1, rm_jtf_sortie.getText().length());

            ProcessObject po = new ProcessObject(parametres, nom);

            return new ProcessObject[]{po};
        }
    }
}
