/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.puzzle.puzzlecore.gui.contexttree;

import java.awt.BorderLayout;
import java.io.Serializable;
import java.util.logging.Logger;
import org.geotools.gui.swing.contexttree.JContextTree;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.Utilities;
import org.puzzle.puzzlecore.struct.CORE;
import org.puzzle.puzzlecore.struct.ContextManager;

/**
 * Top component which displays something.
 */
final class ContextTreeTopComponent extends TopComponent {

    private JContextTree tree = null;

    
    private static ContextTreeTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";

    private static final String PREFERRED_ID = "ContextTreeTopComponent";

    private ContextTreeTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(ContextTreeTopComponent.class, "CTL_ContextTreeTopComponent"));
        setToolTipText(NbBundle.getMessage(ContextTreeTopComponent.class, "HINT_ContextTreeTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
                
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized ContextTreeTopComponent getDefault() {
        if (instance == null) {
            instance = new ContextTreeTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the ContextTreeTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized ContextTreeTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(ContextTreeTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof ContextTreeTopComponent) {
            return (ContextTreeTopComponent) win;
        }
        Logger.getLogger(ContextTreeTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER;
    }

    @Override
    public void componentOpened() {
        removeAll();
        if(tree == null){
            tree = CORE.getContextManager().getContextTree();
        }
        
        add(BorderLayout.CENTER,tree);
    }

    @Override
    public void componentClosed() {
        removeAll();
        tree = null;
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return ContextTreeTopComponent.getDefault();
        }
    }
}
